# Generated by Django 5.0.4 on 2024-05-15 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tasks', '0003_collaboration_task_task_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboration',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='collaboration',
            name='participants',
        ),
        migrations.AddField(
            model_name='collaboration',
            name='participants',
            field=models.ManyToManyField(related_name='participates_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
